# -*- coding: utf-8 -*-
"""Normalization in pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rNUak7nZfmGn82p9HgLWmuuNXqQSJchO
"""

import numpy as np
import pandas as pd

#Normalization--->Min_value=0, max_value=1

df=pd.read_csv("/content/covid_toy - covid_toy.csv")

df.head(3)

df.isnull().sum()

from sklearn.impute import SimpleImputer

si=SimpleImputer()

df['fever']=si.fit_transform(df[['fever']])

df.isnull().sum()

df['gender']=df['gender'].map({'Male':0,'Female':1})
df['cough']=df['cough'].map({'Mild':0,'Strong':1})
df['city']=df['city'].map({'Kolkata':0,'Bangalore':1,'Delhi':2, 'Mumbai':3})
df['has_covid']=df['has_covid'].map({'Yes':0,'No':1})

df.head(2)

x=df.drop(columns=['has_covid'])
y=df['has_covid']

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test= train_test_split(x,y,test_size=0.2,random_state=42)

np.round(x_train.describe(),2)

from sklearn.preprocessing import MinMaxScaler

mn=MinMaxScaler()

x_train_mn = mn.fit_transform(x_train)

x_train_new=pd.DataFrame(x_train_mn,columns=x_train.columns)

np.round(x_train_new.describe(),2)

df=pd.read_csv("/content/placement - placement.csv")

df.head(4)

df.isnull().sum()

x=df.drop(columns=['placed'])
y=df['placed']

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test= train_test_split(x,y,test_size=0.2,random_state=42)

from sklearn.preprocessing import MinMaxScaler

mn=MinMaxScaler()

x_train_mn = mn.fit_transform(x_train)

x_train_new= pd.DataFrame(x_train_mn, columns=x_train.columns)

np.round(x_train_new.describe(),2)

